version: '3'
services:
    db:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: password

    app:
        build: .
        command: bundle exec rails s
        volumes:
            - .:/railsApp
        depends_on:
        - db

    web:
        build: ./containers/nginx
        volumes:
            - .:/railsApp
        ports:
            - "3000:3000"
        depends_on:
            - app